---
- name: Execute Python script to filter a list of integers
  hosts: localhost
  tasks:
    - name: Copy the Python script to the remote host
      copy:
        src: /mnt/c/DevOps/filter_integers.py
        dest: /tmp/filter_integers.py

    - name: Execute the Python script
      command: python3 /tmp/filter_integers.py
      register: script_output

    - name: Display the output of the Python script
      debug:
        msg: "{{ script_output.stdout }}"
